version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - bridge
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    networks:
      - bridge

networks:
  bridge:
