# Base image
FROM node:16 as builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# build the API
RUN npm run build:api:prod

# Start the API
CMD ["node", "dist/apps/api/main.js"]
